/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cube.gltf')
  return (
    <group ref={group} {...props}>
      <mesh material={materials.Material} geometry={nodes.Cube.geometry} />
    </group>
  )
}

useGLTF.preload('/cube.gltf')
