/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/stage.gltf");
  return (
    <group ref={group} {...props}>
      <mesh
        material={nodes.Cube004.material}
        geometry={nodes.Cube004.geometry}
        position={[1.95, 0.45, 0.95]}
        scale={[0.05, 0.5, 0.05]}
      />
      <mesh
        material={nodes.Cube006.material}
        geometry={nodes.Cube006.geometry}
        position={[-1.95, 0.45, 0.95]}
        scale={[0.05, 0.5, 0.05]}
      />
      <mesh
        material={materials.Material}
        geometry={nodes.Cube.geometry}
        position={[1, 1, 0]}
      />
      <mesh
        material={materials.Material}
        geometry={nodes.Cube005.geometry}
        position={[-1, 1, 0]}
      />
      <mesh
        material={materials.Wood_Black}
        geometry={nodes.Cube002.geometry}
        position={[0, 1.08, -0.97]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.03, 1.6, 0.03]}
      />
    </group>
  );
}

useGLTF.preload("/stage.gltf");
